-- Your SQL goes here

ALTER TABLE posts ADD COLUMN description TEXT NOT NULL;
ALTER TABLE posts ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE posts ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE posts ADD COLUMN slug TEXT NOT NULL UNIQUE;